ERROR - 2023-10-29 06:15:21 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\ewms\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ewms\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ewms', 3306, '', 0)
#1 C:\xampp\htdocs\ewms\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ewms\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ewms\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ewms\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ewms\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\ewms\app\validation\UserRules.php(11): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\ewms\system\Validation\Validation.php(278): App\Validation\UserRules->validateUser('Test@102030', 'username,passwo...', Array, NULL, 'password')
#8 C:\xampp\htdocs\ewms\system\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('password', 'Password', 'Test@102030', Array, Array)
#9 C:\xampp\htdocs\ewms\system\Controller.php(141): CodeIgniter\Validation\Validation->run()
#10 C:\xampp\htdocs\ewms\app\Controllers\User.php(27): CodeIgniter\Controller->validate(Array, Array)
#11 C:\xampp\htdocs\ewms\system\CodeIgniter.php(932): App\Controllers\User->login()
#12 C:\xampp\htdocs\ewms\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#13 C:\xampp\htdocs\ewms\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\ewms\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\ewms\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ewms\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ewms\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ewms\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ewms\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ewms\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\ewms\app\validation\UserRules.php(11): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\ewms\system\Validation\Validation.php(278): App\Validation\UserRules->validateUser('Test@102030', 'username,passwo...', Array, NULL, 'password')
#7 C:\xampp\htdocs\ewms\system\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('password', 'Password', 'Test@102030', Array, Array)
#8 C:\xampp\htdocs\ewms\system\Controller.php(141): CodeIgniter\Validation\Validation->run()
#9 C:\xampp\htdocs\ewms\app\Controllers\User.php(27): CodeIgniter\Controller->validate(Array, Array)
#10 C:\xampp\htdocs\ewms\system\CodeIgniter.php(932): App\Controllers\User->login()
#11 C:\xampp\htdocs\ewms\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#12 C:\xampp\htdocs\ewms\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\ewms\index.php(67): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2023-10-29 06:15:21 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `UserName` = :UserName:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\validation\UserRules.php(11): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\Validation\Validation.php(278): App\Validation\UserRules->validateUser('Test@102030', 'username,password', [...], null, 'password')
 7 SYSTEMPATH\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('password', 'Password', 'Test@102030', [...], [...])
 8 SYSTEMPATH\Controller.php(141): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\User.php(27): CodeIgniter\Controller->validate([...], [...])
10 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\User->login()
11 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
12 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-29 06:16:30 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\ewms\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 C:\xampp\htdocs\ewms\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ewms', 3306, '', 0)
#1 C:\xampp\htdocs\ewms\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ewms\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ewms\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ewms\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ewms\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\ewms\app\validation\UserRules.php(11): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\ewms\system\Validation\Validation.php(278): App\Validation\UserRules->validateUser('Test@102030', 'username,passwo...', Array, NULL, 'password')
#8 C:\xampp\htdocs\ewms\system\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('password', 'Password', 'Test@102030', Array, Array)
#9 C:\xampp\htdocs\ewms\system\Controller.php(141): CodeIgniter\Validation\Validation->run()
#10 C:\xampp\htdocs\ewms\app\Controllers\User.php(27): CodeIgniter\Controller->validate(Array, Array)
#11 C:\xampp\htdocs\ewms\system\CodeIgniter.php(932): App\Controllers\User->login()
#12 C:\xampp\htdocs\ewms\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#13 C:\xampp\htdocs\ewms\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\ewms\index.php(67): CodeIgniter\CodeIgniter->run()
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\ewms\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\ewms\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ewms\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ewms\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ewms\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ewms\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\ewms\app\validation\UserRules.php(11): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\ewms\system\Validation\Validation.php(278): App\Validation\UserRules->validateUser('Test@102030', 'username,passwo...', Array, NULL, 'password')
#7 C:\xampp\htdocs\ewms\system\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('password', 'Password', 'Test@102030', Array, Array)
#8 C:\xampp\htdocs\ewms\system\Controller.php(141): CodeIgniter\Validation\Validation->run()
#9 C:\xampp\htdocs\ewms\app\Controllers\User.php(27): CodeIgniter\Controller->validate(Array, Array)
#10 C:\xampp\htdocs\ewms\system\CodeIgniter.php(932): App\Controllers\User->login()
#11 C:\xampp\htdocs\ewms\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#12 C:\xampp\htdocs\ewms\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\ewms\index.php(67): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2023-10-29 06:16:30 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `UserName` = :UserName:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\validation\UserRules.php(11): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\Validation\Validation.php(278): App\Validation\UserRules->validateUser('Test@102030', 'username,password', [...], null, 'password')
 7 SYSTEMPATH\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('password', 'Password', 'Test@102030', [...], [...])
 8 SYSTEMPATH\Controller.php(141): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\User.php(27): CodeIgniter\Controller->validate([...], [...])
10 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\User->login()
11 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
12 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-29 06:26:14 --> Cannot call constructor
in APPPATH\Controllers\Sys.php on line 227.
 1 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Sys->__construct()
 2 SYSTEMPATH\CodeIgniter.php(488): CodeIgniter\CodeIgniter->createController()
 3 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
